


INSERT INTO `extensionicons`
(`Id`, `IsVisible`, `Slug`, `Title`, `Image`, `Description`, `Link`, `Version`, `Author`, `Email`, `Website`, `Count`, `CreatedDate`, `UpdatedDate`)

VALUES
(1, 1, 'icons-set-anotherdimension-ex','Icons Set (AnotherDimension-Ex)', 'https://raw.githubusercontent.com/ImageGlass/Theme/main/extension-icons/Icon-set.AnotherDimension-Ex/preview-1.jpg','Another beautiful icons set for ImageGlass. See README.md for installation.','https://github.com/ImageGlass/theme/releases/download/8.7/Icon-set.AnotherDimension-Ex.zip','1.0','AnotherDimension-Ex','','https://github.com/AnotherDimension-Ex',16117,'2019-02-10 02:17:11','2019-02-10 00:50:23'),
(2, 1, 'icons-set-kyogrou','Icons Set (KyoGrou)', 'https://raw.githubusercontent.com/ImageGlass/Theme/main/extension-icons/Icon-set.KyoGrou/preview.png','The default beautiful icons set for ImageGlass.','https://github.com/ImageGlass/theme/releases/download/8.7/Icon-set.KyoGrou.zip','1.0','KyoGrou','','https://github.com/KyoGrou',7832,'2019-02-10 02:10:11','2019-02-10 00:40:23'),
(3, 1, 'icons-set-resolute-bay','73 Icons Set (H-one Design)', 'https://raw.githubusercontent.com/ImageGlass/Theme/main/extension-icons/Resolute-Bay.H-one-Design/preview.png','A minimalist, colourful set with emphasis on extension name readability. See README.txt for installation.','https://github.com/ImageGlass/theme/releases/download/8.7/Resolute-Bay.H-one-Design.zip','1.0','H-one Design','','https://github.com/ImageGlass/theme/tree/main/extension-icons/Resolute-Bay.H-one-Design',12152,'2020-06-21 16:10:11','2020-06-21 16:38:45'),
(4, 1, 'adobe-icons-set-xmha97','Adobe file icons set (xmha97)', 'https://raw.githubusercontent.com/xmha97/IGExtIcons/master/Logo.jpg','Adobe file icons for ImageGlass','https://github.com/xmha97/ImageGlassThemes/archive/refs/heads/master.zip','21.2','Muhammad Hussein Ammari','','https://github.com/xmha97/IGExtIcons',9815,'2020-09-06 11:10:11','2022-01-11 01:28:25'),
(5, 1, 'jellies-icon-set-h-one-design','Jellies icon set (H-one-Design)', 'https://raw.githubusercontent.com/ImageGlass/Theme/main/extension-icons/Jellies.H-one-Design/preview.png','A vibrantly colourful candy-like set with emphasis on extension name readability.','https://github.com/ImageGlass/theme/releases/download/8.7/Jellies.H-one-Design.zip','1.0','H-one Design','','https://github.com/ImageGlass/theme/tree/main/extension-icons/Jellies.H-one-Design',3238,'2023-01-23 08:28:11','2023-01-23 08:28:11');
